#!/usr/bin/env bash
# lib/common.sh - shared constants, logging, validation and helper functions
# for the M3U8 Livestream Server project. Sourced by install.sh, uninstall.sh,
# status.sh, m3u8-manager and the other lib/*.sh files. Never executed directly.

if [ -n "${M3U8_COMMON_LOADED:-}" ]; then
    return 0 2>/dev/null || exit 0
fi
M3U8_COMMON_LOADED=1

set -Eeuo pipefail

# ---------------------------------------------------------------------------
# Project-wide paths and constants. Keep every other script pointed at these
# instead of hard-coding paths, so the on-disk layout only lives in one place.
# ---------------------------------------------------------------------------
M3U8_PROJECT_NAME="M3U8 Livestream Server"
M3U8_INSTALL_DIR="/opt/m3u8-server"
M3U8_CONFIG_DIR="/etc/m3u8-server"
M3U8_STREAMS_DIR="${M3U8_CONFIG_DIR}/streams"
M3U8_BACKUP_DIR="${M3U8_CONFIG_DIR}/backups"
M3U8_NGINX_GEN_DIR="${M3U8_CONFIG_DIR}/nginx"
M3U8_SERVER_CONF="${M3U8_CONFIG_DIR}/server.conf"
M3U8_STREAMKEYS_MAP="${M3U8_NGINX_GEN_DIR}/streamkeys.map"
M3U8_LOG_FILE="${M3U8_CONFIG_DIR}/install.log"

M3U8_WEB_ROOT="/var/www/m3u8-server"
M3U8_HLS_DIR="${M3U8_WEB_ROOT}/hls"
M3U8_CHANNELS_JSON="${M3U8_WEB_ROOT}/channels.generated.json"

M3U8_NGINX_CONF="/etc/nginx/nginx.conf"
M3U8_NGINX_RTMP_D="/etc/nginx/rtmp.d"
M3U8_NGINX_RTMP_CONF="${M3U8_NGINX_RTMP_D}/m3u8-server.conf"
M3U8_NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
M3U8_NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
M3U8_NGINX_SITE_NAME="m3u8-server.conf"
M3U8_NGINX_SITE_FILE="${M3U8_NGINX_SITES_AVAILABLE}/${M3U8_NGINX_SITE_NAME}"
M3U8_NGINX_SITE_LINK="${M3U8_NGINX_SITES_ENABLED}/${M3U8_NGINX_SITE_NAME}"

M3U8_AUTH_PORT="8899"
M3U8_RTMP_PORT="1935"
M3U8_RTMP_APP_DEFAULT="live"
# "stream-key" (default, secure) checks every publish against the
# generated allow list; "off" accepts any publish unconditionally and
# exists only for diagnostics/emergency troubleshooting - never the
# installer default, never silently switched to on failure.
M3U8_AUTH_MODE_DEFAULT="stream-key"

M3U8_MANAGER_LINK="/usr/local/bin/m3u8-manager"
M3U8_STATUS_LINK="/usr/local/bin/m3u8-status"

M3U8_SUPPORTED_UBUNTU=("18.04" "20.04" "22.04" "24.04" "26.04")

# ---------------------------------------------------------------------------
# Relay subsystem (Phase B) - kept entirely separate from the RTMP-publish
# path above. A relay pulls an existing source (local file, remote HLS,
# RTMP/RTMPS, RTSP, HTTP media) and republishes it as this server's own
# HLS output.
#
# Uses a DEDICATED system account (m3u8-relay), never www-data: relay
# config can hold source-URL credentials/tokens, and the Nginx worker
# identity has no legitimate reason to read them. The persistent config
# in M3U8_RELAYS_DIR stays root:root/700/600 - only root (the manager)
# and the relay-runner's brief root-context bootstrap can read it. The
# runner reads it, then permanently drops to m3u8-relay via setpriv
# before FFmpeg (the process that actually talks to the network) ever
# starts - see lib/relay-runner.sh. FFmpeg itself never runs as root.
# ---------------------------------------------------------------------------
M3U8_RELAYS_DIR="${M3U8_CONFIG_DIR}/relays"
M3U8_MEDIA_DIR="/var/lib/m3u8-server/media"
M3U8_RELAY_HLS_DIR="${M3U8_HLS_DIR}/relay"
M3U8_RELAY_RUNNER="${M3U8_INSTALL_DIR}/lib/relay-runner.sh"
M3U8_RELAY_SYSTEMD_TEMPLATE="/etc/systemd/system/m3u8-relay@.service"
M3U8_RELAY_USER="m3u8-relay"
M3U8_RELAY_SOURCE_TYPES=("local" "http" "hls" "rtmp" "rtmps" "rtsp")
M3U8_RELAY_HLS_SEGMENT_SECONDS="5"
M3U8_RELAY_HLS_LIST_SIZE="6"
# Deliberately a SEPARATE public manifest from M3U8_CHANNELS_JSON (the
# RTMP-publish one): different subsystem, different trust model - a
# relay's source URL must never end up anywhere public, so keeping the
# two manifests generated by entirely separate code paths is a safety
# property, not just organization.
M3U8_RELAY_CHANNELS_JSON="${M3U8_WEB_ROOT}/relays.generated.json"

# Resolve the directory this project's scripts are running from, whether that
# is the git checkout (pre-install / dev usage) or the installed copy under
# M3U8_INSTALL_DIR. Every script that sources common.sh should set
# M3U8_SCRIPT_DIR *before* sourcing so PROJECT_ROOT can be derived here.
if [ -z "${M3U8_PROJECT_ROOT:-}" ]; then
    M3U8_PROJECT_ROOT="$(cd "${M3U8_SCRIPT_DIR:-.}/.." && pwd)"
fi

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
_m3u8_ts() { date '+%Y-%m-%d %H:%M:%S'; }

_m3u8_log_line() {
    local level="$1"; shift
    local line="[${level}] $*"
    # Always to stderr: log/status output must never be captured by a
    # caller doing name="$(some_function ...)" to get a real return value.
    printf '%s\n' "$line" >&2
    if [ -w "$(dirname "$M3U8_LOG_FILE")" ] 2>/dev/null || [ -f "$M3U8_LOG_FILE" ] 2>/dev/null; then
        printf '%s %s\n' "$(_m3u8_ts)" "$line" >>"$M3U8_LOG_FILE" 2>/dev/null || true
    fi
}

log_info()  { _m3u8_log_line "INFO" "$*"; }
log_ok()    { _m3u8_log_line "OK" "$*"; }
log_warn()  { _m3u8_log_line "WARNING" "$*"; }
log_error() { _m3u8_log_line "ERROR" "$*"; }

die() {
    log_error "$*"
    exit 1
}

# ---------------------------------------------------------------------------
# Privilege / environment checks
# ---------------------------------------------------------------------------
require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        die "This command must be run as root. Try: sudo $0 $*"
    fi
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# ---------------------------------------------------------------------------
# Interactive helpers
# ---------------------------------------------------------------------------
# ask <prompt> <default>
# Prints the default inline and returns the trimmed user answer, or the
# default if the user just presses Enter. Never used for secrets.
ask() {
    local prompt="$1" default="${2:-}" answer
    if [ -n "$default" ]; then
        read -r -p "$prompt [$default]: " answer </dev/tty || answer=""
    else
        read -r -p "$prompt: " answer </dev/tty || answer=""
    fi
    answer="${answer#"${answer%%[![:space:]]*}"}"
    answer="${answer%"${answer##*[![:space:]]}"}"
    if [ -z "$answer" ]; then
        printf '%s' "$default"
    else
        printf '%s' "$answer"
    fi
}

# confirm <prompt> [default: y|n]
# Returns 0 for yes, 1 for no.
confirm() {
    local prompt="$1" default="${2:-n}" answer suffix
    if [ "$default" = "y" ]; then suffix="[Y/n]"; else suffix="[y/N]"; fi
    read -r -p "$prompt $suffix: " answer </dev/tty || answer=""
    answer="$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')"
    if [ -z "$answer" ]; then answer="$default"; fi
    [ "$answer" = "y" ] || [ "$answer" = "yes" ]
}

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
# A domain must look like a real DNS hostname before we hand it to certbot.
is_valid_domain() {
    local domain="$1"
    [[ "$domain" =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$ ]]
}

is_valid_email() {
    local email="$1"
    [[ "$email" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

# Channel/stream names double as filenames and URL path segments, so they are
# restricted to a conservative safe set. Reserved words are blocked because
# they collide with real routes served by the generated nginx config.
is_valid_channel_name() {
    local name="$1"
    [[ "$name" =~ ^[a-z0-9][a-z0-9_-]{1,31}$ ]] || return 1
    case "$name" in
        hls|watch|channels.generated.json|relays.generated.json|api|admin|auth|live|index|index.html|relay) return 1 ;;
    esac
    return 0
}

# Relay names share the exact same safe character set/reserved-word rules
# as channel names (both end up as URL path segments and directory names).
is_valid_relay_name() {
    is_valid_channel_name "$1"
}

is_valid_rtmp_app_name() {
    local name="$1"
    [[ "$name" =~ ^[a-z0-9][a-z0-9_-]{1,31}$ ]]
}

is_valid_auth_mode() {
    [ "$1" = "stream-key" ] || [ "$1" = "off" ]
}

is_valid_relay_source_type() {
    local t="$1" v
    for v in "${M3U8_RELAY_SOURCE_TYPES[@]}"; do
        [ "$v" = "$t" ] && return 0
    done
    return 1
}

is_valid_relay_mode() {
    [ "$1" = "copy" ] || [ "$1" = "transcode" ]
}

is_valid_rtsp_transport() {
    [ "$1" = "tcp" ] || [ "$1" = "udp" ] || [ "$1" = "auto" ]
}

# Only used to sanity-check a source URL/path before ever building an
# FFmpeg argument list from it - never interpolated into a shell string.
# Rejects control characters and anything that looks like a shell
# metacharacter or path-traversal attempt for local paths; otherwise
# permissive, since legitimate URLs vary widely (query strings, tokens).
is_valid_relay_source_url() {
    local url="$1"
    [ -n "$url" ] || return 1
    [ "${#url}" -le 2048 ] || return 1
    case "$url" in
        *$'\n'*|*$'\r'*) return 1 ;;
        *';'*|*'|'*|*'`'*|*'$('*|*'&&'*) return 1 ;;
    esac
    return 0
}

# Stream keys are written verbatim into a generated Nginx map ("KEY 1;"),
# so the character set is restricted to what can never break map/config
# syntax (no quotes, semicolons, whitespace, or Nginx variable syntax) or
# need escaping in a URL/shell context. The lower bound (8) rejects
# obviously-weak manual input; the upper bound (128) keeps the resulting
# map hash bucket size requirement predictable (see lib/nginx.sh, where
# map_hash_bucket_size is sized to comfortably fit keys up to this length).
# Project-generated keys are 48 lowercase-hex characters and are always
# well inside this range.
is_valid_stream_key() {
    local key="$1"
    [[ "$key" =~ ^[A-Za-z0-9_-]{8,128}$ ]]
}

# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------
# Generates a 48-character lowercase hex stream key from the kernel CSPRNG.
# Hex-only output is intentionally safe to embed in nginx config, filenames,
# and URL paths without further escaping.
generate_stream_key() {
    if command_exists openssl; then
        openssl rand -hex 24
    else
        head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

# ---------------------------------------------------------------------------
# Filesystem helpers
# ---------------------------------------------------------------------------
# render_template <template_file> <dest_file> <mode> "KEY=value" ...
# Simple __KEY__ substitution using bash string replacement, so paths and
# URLs containing '/' never break a sed delimiter. Used for both Nginx
# config generation and the relay systemd unit template.
render_template() {
    local template="$1" dest="$2" mode="$3"; shift 3
    local content pair key value
    content="$(cat "$template")"
    for pair in "$@"; do
        key="${pair%%=*}"
        value="${pair#*=}"
        content="${content//__${key}__/${value}}"
    done
    printf '%s\n' "$content" | atomic_write "$dest" "$mode"
}

# Creates a timestamped backup copy of a file if it exists. Prints the backup
# path (or nothing if there was no source file to back up).
backup_file() {
    local src="$1" dest
    [ -e "$src" ] || return 0
    dest="${src}.bak.$(date '+%Y%m%d%H%M%S')"
    cp -a "$src" "$dest"
    printf '%s' "$dest"
}

# Writes content to a file atomically: write to a temp file in the same
# directory, then rename over the destination. Avoids leaving a half-written
# config file behind if the process is interrupted mid-write.
atomic_write() {
    local dest="$1" mode="${2:-644}" tmp
    tmp="$(mktemp "${dest}.tmp.XXXXXX")"
    cat >"$tmp"
    chmod "$mode" "$tmp"
    mv -f "$tmp" "$dest"
}

ensure_dir() {
    local dir="$1" mode="${2:-755}" owner="${3:-}"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    chmod "$mode" "$dir"
    if [ -n "$owner" ]; then
        chown "$owner" "$dir"
    fi
}

# ---------------------------------------------------------------------------
# Key/value config file helpers (used for server.conf and streams/*.conf)
# ---------------------------------------------------------------------------
# Reads a single KEY=value from a simple config file without sourcing it
# (sourcing arbitrary files would let a corrupted config file execute code).
conf_get() {
    local file="$1" key="$2" line
    [ -f "$file" ] || return 1
    line="$(grep -E "^${key}=" "$file" 2>/dev/null | tail -n1)" || true
    [ -n "$line" ] || return 1
    line="${line#"${key}="}"
    line="${line%$'\r'}"
    if [[ "$line" == \"*\" ]]; then
        line="${line#\"}"
        line="${line%\"}"
    fi
    printf '%s' "$line"
}

# Sets KEY="value" in a simple config file, creating the file or the key if
# needed, and rewriting the value in place if the key already exists.
conf_set() {
    local file="$1" key="$2" value="$3" tmp escaped dir
    escaped="${value//\"/\\\"}"
    dir="$(dirname "$file")"
    # Only create the directory if missing; never reset the mode of an
    # existing one (it may intentionally be 700/750 to protect stream keys).
    [ -d "$dir" ] || mkdir -p "$dir"
    if [ -f "$file" ] && grep -qE "^${key}=" "$file"; then
        tmp="$(mktemp "${file}.tmp.XXXXXX")"
        awk -v k="$key" -v v="${key}=\"${escaped}\"" \
            'BEGIN{FS="="} $1==k{print v; next} {print}' "$file" >"$tmp"
        mv -f "$tmp" "$file"
    else
        printf '%s="%s"\n' "$key" "$escaped" >>"$file"
    fi
}

# ---------------------------------------------------------------------------
# Package management
# ---------------------------------------------------------------------------
APT_UPDATED=0

apt_update_once() {
    if [ "$APT_UPDATED" -eq 0 ]; then
        log_info "Updating package metadata (apt-get update)..."
        DEBIAN_FRONTEND=noninteractive apt-get update -qq
        APT_UPDATED=1
    fi
}

# Returns 0 only if dpkg reports this package as *currently* installed.
# A bare `dpkg -s <pkg>` exit code is NOT sufficient for this: dpkg -s
# returns 0 as long as ANY record exists for the package, including a
# "deinstall ok config-files" state (removed but not purged) - a real
# state seen on some cloud providers' minimal Ubuntu images (this is
# exactly what caused ufw to be silently skipped during install on a real
# Ubuntu 24.04 test: dpkg had a stale record, so apt_install believed it
# was already present). Always check the actual Status field.
package_installed() {
    local status
    status="$(dpkg-query -W -f='${Status}' "$1" 2>/dev/null)" || return 1
    [[ "$status" == *"install ok installed"* ]]
}

package_available() {
    apt_update_once
    apt-cache show "$1" >/dev/null 2>&1
}

# apt_install <pkg> [pkg...]
# Installs only packages that are not already present (per package_installed,
# not a raw dpkg exit code).
apt_install() {
    local pkgs=() pkg
    for pkg in "$@"; do
        if ! package_installed "$pkg"; then
            pkgs+=("$pkg")
        fi
    done
    if [ "${#pkgs[@]}" -eq 0 ]; then
        log_info "Already installed: $*"
        return 0
    fi
    apt_update_once
    log_info "Installing packages: ${pkgs[*]}"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${pkgs[@]}"
}

# ensure_command <command> <package> [package...]
# Guarantees <command> is actually runnable, installing the given
# package(s) if needed. Unlike relying on apt_install/dpkg state alone,
# this checks the real binary afterward - the only thing that actually
# matters to the rest of the script - and reports failure via return
# status rather than assuming success. Does not die: callers decide
# whether a missing command is fatal (e.g. nginx) or something to
# gracefully degrade around (e.g. ufw).
ensure_command() {
    local cmd="$1"; shift
    command_exists "$cmd" && return 0
    apt_install "$@" || true
    command_exists "$cmd"
}

# version_ge <a> <b>
# True if dotted version <a> is greater than or equal to <b>, using a real
# numeric version sort (GNU coreutils `sort -V`) rather than a fragile
# lexical string comparison (which gets "1.9" vs "1.10" wrong).
version_ge() {
    [ "$1" = "$2" ] && return 0
    local newest
    newest="$(printf '%s\n%s\n' "$1" "$2" | sort -V | tail -n1)"
    [ "$newest" = "$1" ]
}

# Prints the installed systemd's bare numeric version (e.g. "245"), or
# nothing if it can't be determined. Used to conditionally include unit
# hardening directives that are newer than the oldest supported Ubuntu
# release's systemd, so a unit file generated on a new release never
# includes a directive an older-but-still-supported release would reject.
detect_systemd_version() {
    command_exists systemctl || return 1
    systemctl --version 2>/dev/null | head -n1 | grep -oE '[0-9]+' | head -n1
}

# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------
public_ip() {
    curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null \
        || curl -fsSL --max-time 5 https://ifconfig.me 2>/dev/null \
        || true
}

print_banner() {
    local title="$1"
    printf '========================================\n'
    printf '%s\n' "$title"
    printf '========================================\n'
}

# Shared PASS/WARNING/FAIL reporters, used by lib/diagnostics.sh and
# lib/selftest.sh alike so neither has an ordering dependency on the other.
_diag_pass() { printf '[PASS]    %s\n' "$1"; }
_diag_warn() { printf '[WARNING] %s\n' "$1"; }
_diag_fail() { printf '[FAIL]    %s\n' "$1"; }

port_listening() {
    local port="$1"
    if command_exists ss; then
        ss -tln 2>/dev/null | awk '{print $4}' | grep -qE "[.:]${port}\$"
    elif command_exists netstat; then
        netstat -tln 2>/dev/null | awk '{print $4}' | grep -qE "[.:]${port}\$"
    else
        return 2
    fi
}
